<?php $title = 'GBAF | Nos conditions'; ?>

<?php ob_start(); ?>
<div class="container">
	<h1 class="primary_h1 mb-5">CONDITIONS D'UTILISATION</h1>
	<p>Merci de lire ces conditions attentivement avant d'utiliser les Services GBAF. En utilisant les Services GBAF, vous acceptez d'être soumis aux présentes conditions. Nous offrons un large panel de Services GBAF et il se peut que des conditions additionnelles s'appliquent. Quand vous utilisez un Service GBAF (par exemple, Votre Profil, les Chèques-Cadeaux ou les Applications GBAF pour mobile), vous êtes aussi soumis aux termes, lignes directrices et conditions applicables à ce Service GBAF (« Conditions du Service »). Si ces Conditions d'Utilisation entrent en contradiction avec ces Conditions du Service, les Conditions du Service prévaudront.
	<br><br>
	Procédure et formulaire de notification de violation de droits.
	<br><br>
	Procédure et Formulaire de notification en vue de notifier un contenu injurieux ou diffamatoire.
	</p>

	<ol>
		<li class="mb-1">COMMUNICATIONS ELECTRONIQUES</li>
		<p>Quand vous utilisez un quelconque Service GBAF ou que vous nous envoyez des courriers électroniques, SMS ou autres communications depuis vos équipements fixes ou mobiles, vous communiquez avec nous électroniquement. Nous communiquerons avec vous électroniquement par divers moyens, tels que par courrier électronique, SMS, messages de notification dans l'application ou en postant des courriers électroniques ou des communications sur le site internet ou à travers les autres Services GBAF, tels que notre Gestionnaire de communication. A des fins contractuelles, vous acceptez que tous les accords, informations, divulgations et autres communications que nous vous enverrons électroniquement remplissent toutes les obligations légales des communiquer par écrit, à moins qu'une loi impérative spécifique impose un autre mode de communication.</p>

		<li class="mb-1">RECOMMANDATIONS ET PERSONNALISATION</li>
		<p>Dans le cadre des Services GBAF, nous vous recommanderons des fonctionnalités, des produits et des services, comprenant des publicités de tiers, qui sont susceptibles de vous intéresser, nous identifierons vos préférences et nous personnaliserons votre expérience.</p>

		<li class="mb-1">PROPRIETE INTELLECTUELLE, DROIT D'AUTEUR, ET PROTECTION DES BASES DE DONNEES</li>
		<p>Tout le contenu présent ou rendu disponible à travers les Services GBAF, tels que les textes, les graphiques, les logos, les boutons, les images, les morceaux de musique, les téléchargements numériques, et les compilations de données, est la propriété d'GBAF, de ses sociétés affiliées ou de ses fournisseurs de contenu et est protégé par le droit luxembourgeois et international de la propriété intellectuelle, d'auteur et de protection des bases de données. La compilation de tout le contenu présent ou rendu disponible à travers les Services GBAF est la propriété exclusive d'GBAF et est protégé par le droit luxembourgeois et international de la propriété intellectuelle et de protection des bases de données.
		<br>
		Vous ne devez pas extraire et/ou réutiliser de façon systématique des parties du contenu de tout Service GBAF sans notre autorisation expresse et écrite. En particulier, vous ne devez pas utiliser de robot d'aspiration de données, ou tout autre outil similaire de collecte ou d'extraction de données pour extraire (en une ou plusieurs fois), pour réutiliser une partie substantielle d'un quelconque Service GBAF, sans notre accord express et écrit. Vous ne devez pas non plus créer et/ou publier vos propres bases de données qui comporteraient des parties substantielles (ex : nos prix et nos listes de produits) d'un Service GBAF sans notre accord express et écrit.</p>

		<li class="mb-1">MARQUES DEPOSEES</li>
		<p>Cliquer ici pour voir une liste non exhaustive des marques déposées par GBAF. Par ailleurs, les graphiques, logos, en-têtes de page, boutons, scripts et noms de services inclus ou rendus disponibles à travers un Service GBAF sont des marques ou visuels d'GBAF. Les marques et visuels d'GBAF ne peuvent pas être utilisés pour des produits ou services qui n'appartiennent pas à GBAF, ou d'une quelconque manière qui pourrait provoquer une confusion parmi les clients, ou d'une quelconque manière qui dénigre ou discrédite GBAF. Toutes les autres marques qui n'appartiennent pas à GBAF et qui apparaissent sur un quelconque Service GBAF sont la propriété de leurs propriétaires respectifs, qui peuvent, ou non, être affiliés, liés ou parrainés par GBAF.</p>

		<li class="mb-1">BREVETS</li>
		<p>Un ou plusieurs brevets détenus par GBAF s'appliquent aux Services GBAF, à ce site internet et aux fonctionnalités et services accessibles via le site internet et les Services GBAF. Des parties de ce site internet fonctionnent sous licences d'un ou plusieurs brevets. Cliquer ici pour voir une liste non exhaustive des brevets détenus par GBAF et des licences de brevets applicables.</p>

		<li class="mb-1">LICENCE ET ACCES</li>
		<p>Sous réserve du respect des présentes Conditions d'Utilisation et des Conditions des Services et du paiement de tous les sommes applicables, GBAF ou ses fournisseurs de contenu vous accorde une licence limitée, non exclusive, non transférable, non sous licenciable pour l'accès et à l'utilisation personnelle et non commerciale des Services GBAF. Cette licence n'inclut aucun droit d'utilisation d'un Service GBAF ou de son contenu pour la vente ou tout autre utilisation commerciale ; de collecte et d'utilisation d'un listing produit, descriptions, ou prix de produits; de toute utilisation dérivée d'un Service GBAF ou de son contenu ; de tout téléchargement ou copie des informations d'un compte pour un autre commerçant ; ou de toute utilisation de robot d'aspiration de données, ou autre outil similaire de collecte ou d'extraction de données.
		<br>
		Tous les droits qui ne vous ont pas été expressément accordés dans ces Conditions d'Utilisation ou dans les Conditions d'un Service sont réservés et restent à GBAF ou à ses licenciés, fournisseurs, éditeurs, titulaires de droits, ou tout autre fournisseur de contenu. Aucun Service GBAF ou tout ou partie de celui-ci ne doit être reproduit, copié, vendu, revendu, visité ou exploité pour des raisons commerciales sans notre autorisation expresse et écrite.
		<br>
		Vous ne devez pas cadrer ou utiliser des techniques de cadrage (framing) pour insérer toute marque, logo ou autre information commerciale (y compris des images, textes, mises en pages ou formes) d'GBAF sans notre autorisation expresse et écrite. Vous ne devez pas utiliser de méta tags ou tout autre « texte caché » utilisant le nom ou les marques déposées d'GBAF sans notre autorisation expresse et écrite.
		<br>
		Vous ne devez pas faire un mauvais usage d'un Service GBAF. Vous devez utiliser les Services GBAF comme autorisé par la loi. Les licences accordées par GBAF prendront fin si vous ne respectez pas ces Conditions d'Utilisation ou les Conditions des Services.</p>

		<li class="mb-1">VOTRE COMPTE</li>
		<p>Vous pouvez avoir besoin d'un compte personnel GBAF pour utiliser certain Services GBAF, et il peut vous être demandé de vous connecter au compte et d'avoir une méthode de paiement valide associée à celui-ci. En cas de problème pour utiliser la méthode de paiement que vous avez sélectionnée, nous pourrons utiliser toute autre méthode de paiement valide associée à votre compte. Cliquez ici pour gérer vos options de paiement.
		<br>
		Si vous utilisez un quelconque Service GBAF, vous êtes responsable du maintien de la confidentialité de votre compte et mot de passe, des restrictions d'accès à votre ordinateur et autres équipements, et dans la limite de ce qui est autorisé par la loi applicable, vous acceptez d'être responsable de toutes les activités qui ont été menées depuis de votre compte ou avec votre mot de passe. Vous devez prendre toutes les mesures nécessaires pour vous assurer que votre mot de passe reste confidentiel et sécurisé, et devez nous informer immédiatement si vous avez des raisons de croire que votre mot de passe est connu de quelqu'un d'autre, ou si le mot de passe est utilisé ou susceptible d'être utilisé de manière non autorisée. Vous êtes responsable de la validité et du caractère complets des informations que vous nous avez fournies, et devez nous informer de tout changement concernant ces informations. Vous pouvez accéder à vos informations dans la section Votre compte du site internet. Veuillez consulter nos pages d'aide relatives à la Protection de vos informations personnelles pour accéder à vos informations personnelles.
		<br>
		Vous ne devez pas utiliser un quelconque Service GBAF : (i) d'une façon qui causerait, ou serait susceptible de causer une interruption, un dommage, ou une altération d'un Service GBAF, or (ii) dans un but frauduleux, ou en relation avec un crime ou une activité illégale, ou (iii) dans le but provoquer des troubles, nuisances ou causes d'anxiétés.
		<br>
		Nous nous réservons le droit de refuser l'accès, de fermer un compte, de retirer ou de modifier du contenu si vous êtes en violation des lois applicables, de ces Conditions d'utilisation ou tous autres termes, conditions, lignes directrices ou politique d'GBAF.</p>

		<li class="mb-1">COMMENTAIRES, CRITIQUES, COMMUNICATIONS ET AUTRE CONTENU</li>
		<p>Les visiteurs peuvent mettre en ligne des revues, des commentaires ou tout autre contenu ; envoyer des cartes électroniques ou autres communications, et soumettre des suggestions, des idées, des questions ou toute autre information tant que ce contenu n'est pas illégal, obscène, abusif, menaçant, diffamatoire, calomnieux, contrevenant aux droits de propriété intellectuelle, ou préjudiciable à des tiers ou répréhensible et ne consiste pas ou ne contient pas de virus informatiques, de militantisme politique, de sollicitations commerciales, de chaînes de courriers électroniques, de mailing de masse ou toute autre forme de « spam ». Vous ne devez pas utiliser une fausse adresse e-mail, usurper l'identité d'une personne ou d'une entité, ni mentir sur l'origine d'une carte de crédit ou d'un contenu. Nous nous réservons le droit (sans aucune obligation en l'absence d'un Formulaire de Notification valide), de retirer ou de modifier tout contenu. Si vous pensez qu'un contenu ou une annonce de vente sur un quelconque Service GBAF contient un message diffamatoire, ou que vos droits de propriété intellectuelle ont été enfreints par un article ou une information sur le site internet, merci de nous le notifier en complétant le Formulaire de Notification adéquat, et nous y répondrons.
		<br>
		Si vous publiez des commentaires clients, , des questions / réponses ou tout autre contenu généré par vous pour être publié sur le site internet (incluant toute image, vidéo ou enregistrement audio, ensemble le « contenu ») , vous accordez à GBAF, (i) une licence non-exclusive et gratuite pour utiliser, reproduire, , publier, rendre disponible, traduire et modifier ce contenu dans le monde entier(incluant le droit de sous-licencier ces droits à des tiers); et (b) le droit d'utiliser le nom que vous avez utilisé en lien avec ce contenu. Aucuns droits moraux ne sont transférés par l'effet de cette clause.
		<br>
		Vous pouvez supprimer votre contenu de la vue du public ou, lorsque cette fonctionnalité est offerte, modifier les paramètres pour qu'il ne soit visible que par les personnes auxquelles vous en avez donné l'accès. Vous déclarez et garantissez être propriétaire ou avoir les droits nécessaires sur le contenu que vous publiez ; que, à la date de publication du contenu ou du matériel : (i) le contenu et le matériel est exact, (ii) l'utilisation du contenu et du matériel que vous avez fourni ne contrevient pas à l'une des procédures ou lignes directrices d'GBAF et ne portera pas atteinte à toute personne physique ou morale (notamment que le contenu ou le matériel ne sont pas diffamatoires). Vous acceptez d'indemniser GBAF en cas d'action d'un tiers contre GBAF en lien avec le contenu ou le matériel que vous avez fourni, sauf dans le cas où l'éventuelle responsabilité d'GBAF pourrait être recherchée pour ne pas avoir retiré un contenu dont le caractère illicite lui aurait été notifié (Formulaire de Notification), dès lors que cette action aurait pour cause, fondement ou origine le contenu que vous nous avez communiqué.</p>

		<li class="mb-1">REVENDICATIONS DE PROPRIETE INTELLECTUELLE</li>
		<p>GBAF respecte la propriété intellectuelle d'autrui. Si vous pensez qu'un de vos droits de propriété intellectuelle a été utilisé d'une manière qui puisse faire naitre une crainte de violation desdits droits, merci de suivre notre Procédure et formulaire de notification de violation de droits.</p>

		<li class="mb-1">CONDITIONS LOGICIEL GBAF</li>
		<p>S'ajoute à ces Conditions d'Utilisation, les conditions suivantes qui s'appliquent à tous les logiciels (en ce compris les mises à jour ou les évolutions du logiciel et de toute la documentation liée) que nous vous rendons disponibles pour votre utilisation des Services GBAF (ci-après « Logiciels GBAF »).</p>

		<li class="mb-1">AUTRES ENTREPRISES</li>
		<p>Des tiers autres qu'GBAF gèrent des boutiques, proposent des services et vendent des lignes de produits sur ce site internet. De surcroit, nous fournissons des liens vers des sites internet de société affiliées et d'un certain nombre d'entreprises. Nous ne sommes pas responsables de l'examen ou de l'évaluation, et nous ne garantissons pas les offres de ces entreprises ou de ces particuliers, ou le contenu de leurs sites internet. GBAF n'assume aucune responsabilité ou obligation pour les actes, produits ou contenu de ces entreprises ou de ces particuliers ou d'autres tiers. Vous êtes informés quand un tiers est impliqué dans votre transaction, et nous pouvons partager vos informations en lien avec cette transaction avec ce tiers. Vous devez examiner leurs politiques de confidentialité et autres conditions d'utilisation avec attention.</p>

		<li class="mb-1">ROLE D'GBAF</li>
		<p>GBAF permet à des vendeurs tiers de lister et de vendre leurs produits sur GBAF.fr. Dans chacun de ces cas, ceci est indiqué sur la page respective de détail du produit. Bien qu'GBAF, en tant qu'hébergeur, facilite les transactions réalisées sur la place de marché (ou Marketplace) d'GBAF, GBAF n'est ni l'acheteur ni le vendeur des produits des vendeurs tiers. GBAF fournit un lieu de rencontre dans lequel les acheteurs et vendeurs complètent et finalisent leurs transactions. En conséquence, pour la vente de ces produits de vendeurs tiers, un contrat de vente est formé uniquement entre l'acheteur et le vendeur tiers. GBAF n'est pas partie à un tel contrat et n'assume aucune responsabilité ayant pour origine un tel contrat ou découlant de ce contrat de vente. GBAF n'est ni l'agent ni le mandataire des vendeurs tiers. Le vendeur tiers est responsable des ventes de produits et des réclamations ou tout autre problème survenant ou lié au contrat de vente entre lui et l'acheteur. Parce qu'GBAF souhaite que l'acheteur bénéficie d'une expérience d'achat la plus sûre, GBAF offre la Garantie A à Z en plus de tout droit contractuel ou autre.</p>

		<li class="mb-1">NOTRE RESPONSABILITE</li>
		<p>Nous ferons de notre mieux pour assurer la disponibilité des Services GBAF et que les transmissions se feront sans erreurs. Toutefois, du fait de la nature d'internet, ceci ne peut être garanti. De plus, votre accès aux Services GBAF peut occasionnellement être suspendu ou limité pour permettre des réparations, la maintenance, ou ajouter une nouvelle fonctionnalité ou un nouveau service. Nous nous efforcerons de limiter la fréquence et la durée de ces suspensions ou limitations.
		<br>
		Dans le cadre de ses relations avec des professionnels, GBAF n'est pas responsable (i) des pertes qui n'ont pas été causées par une faute de notre part, ou (ii) des pertes commerciales (y compris les pertes de profit, bénéfice, contrats, économies espérées, données, clientèle ou dépenses superflues), ou (iii) toute perte indirecte ou consécutive qui n'étaient pas prévisibles par vous et nous quand vous avez commencé à utiliser le Service GBAF.
		<br>
		Nous ne serons pas tenus pour responsables des délais ou de votre impossibilité à respecter vos obligations en application de ces conditions si le délai ou l'impossibilité résulte d'une cause en dehors de notre contrôle raisonnable. Cette condition n'affecte pas votre droit légal de recevoir les produits envoyés et les services fournis dans un temps raisonnable ou de recevoir un remboursement si les produits ou les services commandés ne peuvent être délivrés dans un délai raisonnable en raison d'une cause hors de notre contrôle raisonnable.
		<br>
		Les lois de certains pays ne permettent pas certaines des limitations énumérées ci-dessus. Si ces lois vous sont applicables, tout ou partie de ces limitations ne vous sont pas applicables, et vous pouvez disposer de droits supplémentaires.
		<br>
		Rien dans ces conditions ne vise à limiter ou n'exclure notre responsabilité en cas de dol, ou en cas de décès ou de préjudice corporel causé(e) par notre négligence ou une faute lourde.</p>

		<li class="mb-1">DROIT APPLICABLE</li>
		<p>Les présentes Conditions d'utilisation sont soumises au droit luxembourgeois (à l'exception de ses dispositions concernant les conflits de loi), et l'application de la Convention de Vienne sur les contrats de vente internationale de marchandises est expressément exclue. Si vous êtes un consommateur et que votre résidence habituelle est située dans un pays de l'Union Européenne, vous bénéficiez également de droits vous protégeant en vertu des dispositions obligatoires de la loi applicable dans votre pays de résidence. Vous, comme nous, acceptons de soumettre tous les litiges occasionnés par la relation commerciale existant entre vous et nous à la compétence non exclusive des juridictions de la ville de Luxembourg, ce qui signifie que pour l'application des présentes Conditions d'utilisation, vous pouvez intenter une action pour faire valoir vos droits de consommateur, au Luxembourg ou dans le pays de l'Union Européenne dans lequel vous résidez. La Commission Européenne met à disposition une plateforme en ligne de résolution des différends à laquelle vous pouvez accéder ici: https://ec.europa.eu/consumers/odr/. Si vous souhaitez attirer notre attention sur un sujet, merci de nous contacter.</p>

		<li class="mb-1">MODIFICATION DU SERVICE OU DES CONDITIONS D'UTILISATION</li>
		<p>Nous nous réservons le droit de faire des modifications sur tout Service GBAF, à nos procédures, à nos termes et conditions, y compris les présentes Conditions d'utilisation à tout moment. Vous êtes soumis aux termes et conditions, procédures et Conditions d'utilisation en vigueur au moment où vous utilisez le Service GBAF. Si une stipulation de ces Conditions d'utilisation est réputée non valide, nulle, ou inapplicable, quelle qu'en soit la raison, cette stipulation sera réputée divisible et n'affectera pas la validité et l'opposabilité des stipulations restantes.</p>

		<li class="mb-1">RENONCIATION</li>
		<p>Si vous enfreignez ces Conditions d'utilisation et que nous ne prenons aucune action, nous serions toujours en droit d'utiliser nos droits et voies de recours dans toutes les autres situations où vous violeriez ces Conditions d'utilisation.</p>

		<li>MINEURS</li>
		<p>Nous ne vendons pas de produits aux mineurs. Nous vendons des produits pour enfants pour des achats par des adultes. Si vous avez moins de 18 ans, vous ne pouvez utiliser un Service GBAF que sous la surveillance d'un parent ou d'un tuteur. Les offres de produits contenant de l'alcool sont destinées à des personnes majeures. Vous devez avoir au moins 18 ans pour acheter de l'alcool ou utiliser toute fonctionnalité du site concernant de l'alcool.</p>

		<li class="mb-1">PROCEDURE ET FORMULAIRE DE NOTIFICATION DE VIOLATION DE DROITS</li>
		<p>Si vous pensez que vos droits ont été violés et que vous êtes éligible aux Registre des Marques, veuillez vous inscrire au service et soumettre votre plainte via le Registre des Marques. Sinon, merci d'utiliser notre Formulaire de Notification. Ce formulaire peut être utilisé pour nous soumettre toute sorte de plainte de propriété intellectuelle y compris, sans toutefois s'y limiter, les plaintes liées aux droits d'auteur, de marques, de dessins et modèles et de brevets. Dès réception d'un Formulaire de Notification, nous pouvons prendre certaines mesures, notamment la suppression d'informations ou d'un article et mettre fin aux infractions répétées dans des circonstances appropriées. Ces mesures seront toutefois prises sous toutes réserves, sans reconnaissance de notre part d'une responsabilité quelconque et sans préjudice de l'exercice de nos droits, actions et moyens de défense. Ceci comprend également le transfert de ce formulaire aux parties concernées par l'infraction alléguée. Vous acceptez d'indemniser GBAF contre toute réclamation de tiers contre GBAF, découlant de, ou dans le cadre de cette notification.
		<br>
		Note concernant les offres des vendeurs tiers : merci de garder à l'esprit que les offres des vendeurs tiers sont seulement hébergées sur GBAF.fr et sont publiées uniquement sous la direction des vendeurs tiers qui peuvent être contactés par leur page « Informations sur le vendeur », accessible depuis toutes leurs offres.
		<br>
		Définition d'ASIN et de ISBN-10 : « ASIN » signifie GBAF Standard Item (or Identification) Number (Numéro d'identification ou d'article standard d'GBAF) et est un identifiant composé de dix (10) caractères. Ce numéro figure dans toute fiche descriptive d'un produit sous le titre « Détails sur le produit ». « ISBN-10 » signifie International Standard Book Number (Numéro de livre standard international) et est un identifiant composé de dix (10) chiffres figurant sur certaines fiches descriptives de livres dans la catégorie « Détails sur le produit ».
		<br>
		Avertissement important : fournir des informations inexactes, trompeuses ou fausses dans un Formulaire de Notification adressé à GBAF engage sa responsabilité civile et/ou pénale. En cas de doute, veuillez contacter un conseiller juridique..
		<br>
		Formulaire de notification : Si vous souhaitez nous notifier la violation de vos droits en relation avec une offre de produit disponible sur le site www.GBAF.fr, nous vous invitons à remplir le Formulaire de notification</p> 

		<li class="mb-1">PROCEDURE ET FORMULAIRE DE NOTIFICATION EN VUE DE NOTIFIER UN CONTENU INJURIEUX OU DIFFAMATOIRE</li>
		<p>Parce que des millions de produits sont listés et que des milliers de commentaires sont hébergés sur GBAF.fr, il ne nous est pas possible de connaître le contenu de tous les produits offerts à la vente, ou de tous les commentaires ou critiques qui sont affichés. En conséquence, nous opérons sous un système de « notice and action » soit « notifier et action ». Si vous pensez qu'un contenu ou une annonce de vente sur le site internet contient un message diffamatoire, merci de nous le notifier immédiatement en complétant la Procédure et le Formulaire de notification en vue de notifier un contenu injurieux ou diffamatoire. Suivez les instructions dans le formulaire de Notification.
		<br>
		Avertissement important : fournir des informations inexactes, trompeuses ou fausses dans la Notification adressée à GBAF peut engager votre responsabilité civile et/ou pénale.
		<br>
		La procédure de notification : Merci de nous envoyer le formulaire ci-dessous, dûment rempli et signé, à l'adresse suivante : Département juridique, NTD, GBAF EU S.à r.l., 38 avenue John F. Kennedy, L-1855 Luxembourg, Grand Duché du Luxembourg.</p>
	</ol>
</div>
<?php $content = ob_get_clean(); ?>

<?php $footer = 'static';?>

<?php require('view/template.php'); ?>